/**
 * 営業実務共通エラーコード
 *
 * エンジン固有の詳細コードを追加する場合も、
 * 呼出し側が共通処理できるよう本定数へ集約する。
 */
export const ErrorCodes = Object.freeze({
  INVALID_STATION: 'ERR_INVALID_STATION',
  INVALID_STATUS: 'ERR_INVALID_STATUS',
  INVALID_TICKET_TYPE: 'ERR_INVALID_TICKET_TYPE',
  INVALID_PASSENGER_TYPE: 'ERR_INVALID_PASSENGER_TYPE',
  INVALID_DISCOUNT_TYPE: 'ERR_INVALID_DISCOUNT_TYPE',
  REFUND_NOT_ALLOWED: 'ERR_REFUND_NOT_ALLOWED',
  RULE_NOT_FOUND: 'ERR_RULE_NOT_FOUND',
  REQUIRED_FIELD: 'ERR_REQUIRED_FIELD',
  ROUTE_NOT_FOUND: 'ERR_ROUTE_NOT_FOUND',
  DISTANCE: 'ERR_DISTANCE',
  INVALID_NUMBER: 'ERR_INVALID_NUMBER',
  JSON_MISSING: 'ERR_JSON_MISSING',
  JSON_LOAD_FAILED: 'ERR_JSON_LOAD_FAILED',
  UNSUPPORTED_OPERATION: 'ERR_UNSUPPORTED_OPERATION'
});

export default ErrorCodes;
