/**
 * 営業実務共通エラーコード
 *
 * エンジン固有の詳細コードを追加する場合も、
 * 呼出し側が共通処理できるよう本定数へ集約する。
 */
export const ErrorCodes = Object.freeze({
  INVALID_STATION: 'ERR_INVALID_STATION',
  INVALID_STATUS: 'ERR_INVALID_STATUS',
  INVALID_TICKET_TYPE: 'ERR_INVALID_TICKET_TYPE',
  INVALID_PASSENGER_TYPE: 'ERR_INVALID_PASSENGER_TYPE',
  INVALID_DISCOUNT_TYPE: 'ERR_INVALID_DISCOUNT_TYPE',
  REFUND_NOT_ALLOWED: 'ERR_REFUND_NOT_ALLOWED',
  RULE_NOT_FOUND: 'ERR_RULE_NOT_FOUND',
  REQUIRED_FIELD: 'ERR_REQUIRED_FIELD',
  ROUTE_NOT_FOUND: 'ERR_ROUTE_NOT_FOUND',
  DISTANCE: 'ERR_DISTANCE',
  INVALID_NUMBER: 'ERR_INVALID_NUMBER',
  JSON_MISSING: 'ERR_JSON_MISSING',
  JSON_LOAD_FAILED: 'ERR_JSON_LOAD_FAILED',
  UNSUPPORTED_OPERATION: 'ERR_UNSUPPORTED_OPERATION',
  INVALID_OPERATION: 'ERR_INVALID_OPERATION',
  INVALID_DATE: 'ERR_INVALID_DATE',
  INVALID_PERIOD: 'ERR_INVALID_PERIOD',
  INVALID_DEPARTURE_STATUS:
    'ERR_INVALID_DEPARTURE_STATUS',
  MASTER_MISSING: 'ERR_MASTER_MISSING',
  MASTER_DUPLICATE: 'ERR_MASTER_DUPLICATE',
  PRIORITY_CONFLICT: 'ERR_PRIORITY_CONFLICT',
  CIRCULAR_REFERENCE: 'ERR_CIRCULAR_REFERENCE',
  COMPANY_DUPLICATE: 'ERR_COMPANY_DUPLICATE',
  LINE_DUPLICATE: 'ERR_LINE_DUPLICATE',
  STATION_DUPLICATE: 'ERR_STATION_DUPLICATE',
  DISTANCE_DUPLICATE: 'ERR_DISTANCE_DUPLICATE',
  REFERENCE_INTEGRITY: 'ERR_REFERENCE_INTEGRITY',
  ORPHAN_STATION: 'ERR_ORPHAN_STATION',
  ORPHAN_LINE: 'ERR_ORPHAN_LINE',
  COMPANY_REFERENCE_NOT_FOUND:
    'ERR_COMPANY_REFERENCE_NOT_FOUND',
  STATION_REFERENCE_NOT_FOUND:
    'ERR_STATION_REFERENCE_NOT_FOUND',
  LINE_REFERENCE_NOT_FOUND:
    'ERR_LINE_REFERENCE_NOT_FOUND',
  DISTANCE_REFERENCE_NOT_FOUND:
    'ERR_DISTANCE_REFERENCE_NOT_FOUND'
});

export default ErrorCodes;
